// Mock data for services
import type { Service } from '@/types';

export const mockServices: Service[] = [
  {
    id: 'service-1',
    name: 'Šišanje',
    description: 'Pranje, šišanje i styling.',
    duration: 45,
    price: 25,
    active: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'service-2',
    name: 'Bojanje',
    description: 'Bojanje cijele kose ili izrast.',
    duration: 90,
    price: 60,
    active: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'service-3',
    name: 'Styling',
    description: 'Feniranje i/ili kovrče.',
    duration: 30,
    price: 20,
    active: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'service-4',
    name: 'Muško šišanje',
    description: 'Pranje i šišanje.',
    duration: 30,
    price: 15,
    active: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'service-5',
    name: 'Dječje šišanje',
    description: 'Za djecu do 12 godina.',
    duration: 25,
    price: 12,
    active: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'service-6',
    name: 'Njega kose',
    description: 'Maska, njega i masaža vlasišta.',
    duration: 30,
    price: 18,
    active: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];
